go-stomp/stomp

- conn.go
- transaction.go
Fixes an issue with write timeouts on sends that require a receipt or are in a transaction.
Also fixes an issue where errors are not returned correctly from transactional sends upon commit.
> Fixes an issue with write timeouts on sends that require a receipt or are in a transaction

- conn.go
- subscribe_options.go
- subscription.go
Not sure if this repo is still active, but thought I'd offer this up since it bit me. Had a lot of trouble with a relatively simple toy program that basically did the following:
* connect
* produce one message
* subscribe
* consume the message
* unsubscribe
* disconnect
Usually manifested as goroutines stuck waiting for messages that never came, or channel write panics/errors. 
Root cause seems to be a few subtle issues & around `Subscription.Unsubscribe`: the call to sendFrame() does not wait for the implicit RECEIPT triggered by the "receipt" header injected on the connection's processLoop goroutine. As a result, we try to close the channel before the RECEIPT has been processed. Then on top of that, even if the RECEIPT does somehow manage to sneak through, `Subscribe.readLoop` also …
> Ensure UNSUBSCRIBE RECEIPTs are handled properly

- conn.go
- subscribe_options.go
- subscription.go
Reverts go-stomp/stomp#37, due to failed tests
> Revert "Ensure UNSUBSCRIBE RECEIPTs are handled properly"

- conn.go
- subscribe_options.go
- subscription.go
@worg this is the follow-up RE: #37, sorry about that. Tests pass for me with these changes.
Two changes to my original approach:
* Move the call to `close(s.C)` back to the `Subscription.readLoop` goroutine. Not sure what I was thinking moving that into Unsubscribe.
* Avoid reading from `s.C` in `Subscription.Unsubscribe` while waiting for the RECEIPT to avoid interfering with consumers that might be interested in ERROR frames: instead use a sync.Cond to wait for the transition to `subStateClosed`.
> Ensure UNSUBSCRIBE RECEIPTs are handled properly (redux)

- conn.go
I have a frame option function that keeps track of retries on a message. At a certain count, I wish to push the message off to another destination for later investigation.
Right now, the destination header is set _after_ option functions are called, so you can't change the destination (or even check what the destination will be). Setting the headers earlier solves that issue, but there may be ramifications I don't fully understand.
> set send frame details earlier

- conn.go
When calling `.Begin()` on a connection it is desirable to handle errors such that if sending the frame fails because of a connection error (or similar) it can be handled prior to actually sending from within the `Transaction`
This PR adds a new `BeginWithError` function that returns the `Transaction` as well as the `error` from the `.sendFrame` call.  (I'm open to a better name)
It also returns the `.sendFrame` result for `.Ack` and `.Nack` such that you can handle errors there as well.
CC @worg
> Allow for error handling during Begin

- conn.go
We recently enabled `-race` in our `go test` invocation and a project using go-stomp began to report data races.  See below for a full example of the data race output.
The data race warning is correct because `sendFrame` doesn't gate the read access of `c.closed` via `c.closeMutex`.
This PR adds the mutex lock/unlock to `sendFrame`.
-----
```
WARNING: DATA RACE
Read at 0x00c000118660 by goroutine 26:
github.com/go-stomp/stomp.(*Conn).sendFrame()
/Users/eborgstrom/go/pkg/mod/github.com/go-stomp/stomp@v2.0.2-0.20181110012836-7ed7cfe401c1+incompatible/conn.go:476 +0x69
github.com/go-stomp/stomp.(*Conn).BeginWithError()
/Users/eborgstrom/go/pkg/mod/github.com/go-stomp/stomp@v2.0.2-0.20181110012836-7ed7cfe401c1+incompatible/conn.go:614 +0xc9
github.com/NerdWallet/yak/go/yak.NewTransaction() …
```
> Ensure the closeMutex is used in sendFrame

- conn.go
Issue: https://github.com/go-stomp/stomp/issues/54
Check for closed connection before sending Subscribe, as it may panic if writeCh has been closed.
> Check connection was closed before sending Subscribe

- frame/encode.go
Using strings.Replace multi times in "encodeValue" and "unencodeValue" function is low efficience, strings.NewReplacer is the more efficient version, here is the benchmark result.
```
/*
$ go test -check.v -check.b -check.bmem
PASS: encode_test.go:32: EncodeSuite.BenchmarkEncodeValue       10000000               223 ns/op             112 B/op          1 allocs/op
PASS: encode_test.go:48: EncodeSuite.BenchmarkEncodeValueOld     5000000               504 ns/op             480 B/op          9 allocs/op
PASS: encode_test.go:40: EncodeSuite.BenchmarkUnencodeValue      5000000               357 ns/op             208 B/op          4 allocs/op
PASS: encode_test.go:56: EncodeSuite.BenchmarkUnencodeValueOld   5000000               556 ns/op             448 B/op          9 allocs/op
OK: 4 passed …
```
> Optimize frame encodeValue unencodeValue, replace with more efficient version

- conn.go
- conn_options.go
- errors.go
Add timeout for Conn.Send function to resolve the deadlock.
For a detailed description of the problem, see issue42.
> add timeout for Conn.Send function to resolve the deadlock

- conn.go
- conn_options.go
This change adds buffer size option to stomp connection and provides the opportunity to specify read/write buffer size
> Add buffer size option to connection

- conn.go
- conn_options.go
- conn_test.go
This PR adds a callback function to ConnOption that can be used to get the headers from the CONNECT response.
Closes https://github.com/go-stomp/stomp/issues/82
> add ConnOption to get CONNECT response headers

- go.mod
- go.sum
Reverts go-stomp/stomp#84
Module file conflicts as pkg.go.dev detects us as v1
> Revert "chore: add go.mod"

- server/client/conn.go
- server/server_test.go
About Heart Beating, [RFC](https://stomp.github.io/stomp-specification-1.2.html#Heart-beating) states that:
> because of timing inaccuracies, the receiver SHOULD be tolerant and take into account an error margin
Most of the client library sends an heart beat when the *cx* delay has been elapsed without sending message. Since the server wait for at max *cx* time it happens that most of the time the client is disconnected before the heart beat actually reach the server.
Multiplying the time by two is a simple way to be more tolerant.
> Increase readTimeout tolerance according to RFC

- server/client/conn.go
Whenever the reading loop was reading data it had the side effect of reseting the *writeTimeout* timer used to send heart beat to the client (this was due to variable scope).
And if the there is several message in a row to read i will postpone the heartbeat to much and result in the connection being closed.
Fix #66
> Fix heart beat problem in server/client/conn.go

- frame/encode.go
- frame/writer.go
Please check! w.writer satisfies both io.Writer and io.StringWriter so no need to use any middleware function to replace symbols.
> Reduce encodeValue allocations

- frame/encode_test.go
`encodeValue` was removed on #100 but the test for it was kept, this PR removes the failing and now unneeded test
> Remove unneeded test

- conn.go
- conn_test.go
- server/client/conn.go
http://stomp.github.io/stomp-specification-1.2.html#ACK
> The ACK frame MUST include an id header matching the ack header of the MESSAGE being acknowledged.
So, instead of "ack" header ACK frame must include "id" header
> fix incorrect header for message id in ACK frames

- conn.go
- subscription.go
According to the standard, the heartbeat for server to client should be MAX(<sx>, <cy>)
> Fix heartbeat

- .github/workflows/test.yml
- conn.go
- conn_options.go
- conn_test.go
My company currently uses go-stomp in a sidecar attached to a main service. We've seen some deadlocks during normal operation, and wanted to monitor a few internal states within go-stomp. This change adds a simple struct defining the sizes of the read and write channels in a `Connection` object, as well as a few super basic counters. Our software would periodically call `Connection.Stats()` and export the data to our metrics systems for further monitoring.
> expose a few connection stats

- subscription.go
I think this is OK because the only point that wakes the `sync.Cond` is _after_ closing the channel and updating the `status` member. There should be no way to close the channel _before_ updating the status. If there were, this code would be racy again.
> stomp: fix Unsubscribe race
